### ISSUE TITLE
Не хватает памяти для Nano

### ISSUE THREAD

**Issue by bugavka** [AlexGyver/WS2812_FX#2]
Привет, эффекты прикольные. Хотел к своей ленте прикрутить, а там 211 светиков, не хватает динамической памяти для загрузки скетча. Как быть? Новый год в опасности! ) Сам не шарю в скетчах :(

**Comment by RUSich101** [comment]
Тоже столкнулся с такой проблемой (правда мне блок питания ещё пришел позже нового года.)
Много памяти отъедают массивы цветов
Их там 2
struct CRGB leds[LED_COUNT];
и
int ledsX[LED_COUNT][3];
 
Первый нужен для библиотеки FastLED. Второй нужен для "кривых алгоритмов". В него зачем-то в некоторых режимах копируется содержимое первого массива. Кроме того, он объявлен как int (4 байта), хотя цвет измеряется от 0 - 255. Достаточно одного байта. Смело можно менять на 
byte ledsX[LED_COUNT][3];

Если после этого не хватит (а мне для 300 штук не хватило), то действуем по следующему алгоритму:
1. комментируем массив.
2. пробуем компилить, смотрим, где используется. 
3. Коментим функцию, где используется.
4. Переходим к пункту 2, пока не скомпилируется.

Таким образом, нерабочими становятся только режимы под номерами 13, 14, 15, 29, 31, 32.

**Comment by bugavka** [comment]
Спасибо
